# Generated by Django 4.1.1 on 2022-10-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_section_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='chapter',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
