# Generated by Django 4.1.1 on 2022-10-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='covers/default.jpg', upload_to='covers'),
        ),
    ]
