# Generated by Django 4.1.1 on 2022-10-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='text',
            name='stats',
        ),
    ]
