# Generated by Django 4.1.1 on 2022-10-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_text_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='text_dict',
        ),
    ]
