# Generated by Django 4.1.1 on 2022-10-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_ext_profile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textstats',
            old_name='stats',
            new_name='stats_string',
        ),
        migrations.AddField(
            model_name='textstats',
            name='acc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='textstats',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textstats',
            name='cpm',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textstats',
            name='wpm',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
