# Generated by Django 4.1.1 on 2022-10-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_stats_textstats_stats_string_textstats_acc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textstats',
            name='chars',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textstats',
            name='errors',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textstats',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textstats',
            name='words',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
