# Generated by Django 4.1.1 on 2022-10-21 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_textstats_chars_textstats_errors_textstats_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textstats',
            name='complete_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
